// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beflrsnhnkrakfjvdsud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZmxyc25obmtyYWtmanZkc3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTgzOTMsImV4cCI6MjA2NTEzNDM5M30.oDzCjZlM9RgPWkJigg4rOTP6vDMmSpoARcxSZ4O-i94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);